In [1]:
import numpy as np

In [31]:
def calculate(lis):
    mat = np.reshape(np.array(lis), (3, 3))
    calculate = {
          'mean': [list(np.mean(mat, axis=0)), list(np.mean(mat, axis=1)), np.mean(mat)],
          'variance': [list(np.var(mat, axis=0)), list(np.var(mat, axis=1)), np.var(mat)],
          'standard deviation': [list(np.std(mat, axis=0)), list(np.std(mat, axis=1)), np.std(mat)],
          'max': [list(np.max(mat, axis=0)), list(np.max(mat, axis=1)), np.max(mat)],
          'min': [list(np.min(mat, axis=0)), list(np.min(mat, axis=1)), np.min(mat)],
          'sum': [list(np.sum(mat, axis=0)), list(np.sum(mat, axis=1)), np.sum(mat)]
}
    return calculate

In [2]:
lis = [0,1,2,3,4,5,6,7,8]
data = np.array(lis)

In [4]:
data = np.reshape(data, (3,3))

In [5]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Column sum

In [6]:
np.sum(data, axis=0)

array([ 9, 12, 15])

### Row sum

In [7]:
np.sum(data, axis=1)

array([ 3, 12, 21])

### Flattened sum

In [8]:
np.sum(data)

36

### Column Min, Max, Variance, Standard Deviation and Mean

In [9]:
np.min(data, axis=0)

array([0, 1, 2])

In [12]:
np.max(data, axis=0)

array([6, 7, 8])

In [15]:
np.std(data, axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [16]:
np.var(data, axis=0)

array([6., 6., 6.])

In [17]:
np.mean(data, axis=0)

array([3., 4., 5.])

### Row Min, Max, Variance, Standard Deviation and Mean

In [10]:
np.min(data, axis=1)

array([0, 3, 6])

In [13]:
np.max(data, axis=1)

array([2, 5, 8])

In [18]:
np.std(data, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [19]:
np.var(data, axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [20]:
np.mean(data, axis=1)

array([1., 4., 7.])

### Flattened Min, Max, Variance, Standard Deviation and Mean

In [11]:
np.min(data)

0

In [14]:
np.max(data)

8

In [21]:
np.std(data)

2.581988897471611

In [22]:
np.var(data)

6.666666666666667

In [23]:
np.mean(data)

4.0

In [32]:
print(calculate(lis))

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}
